### PR TITLE
Add Fermi level line and E-Ef (eV) to the band structure plot

### PR DESCRIPTION
**Pull request by dou-du**
To fix: https://github.com/aiidalab/aiidalab-qe/issues/322

A fermi level line is also added to the band structure plot.

image

### CODE REVIEW

**Comment by dou-du** [comment]
@unkcpz Hi Jusong, please have a look at the code. I have no idea why the annotation is working for the DOS but not for the band structure.

**Comment by unkcpz** [comment]
Sorry @dou-du, I didn't manage time to work on this. Will put it to my TODO list have a look at this.

**Comment by unkcpz** [comment]
I don't have any idea at the moment how to fix this, the code is a bit messy to me and I am not very familiar with js. I'll try to refactor the code a bit and then come back to tackle the issue.

**Review by unkcpz — APPROVED** [review]
LGTM, thanks @dou-du

**Pull request merged**
